/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as HireRouteImport } from './routes/hire'
import { Route as GameRouteImport } from './routes/game'
import { Route as CvRouteImport } from './routes/cv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing.index'
import { Route as WritingSlugRouteImport } from './routes/writing.$slug'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const HireRoute = HireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WritingRoute,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WritingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/game': typeof GameRoute
  '/hire': typeof HireRoute
  '/projects': typeof ProjectsRoute
  '/writing': typeof WritingRouteWithChildren
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/game': typeof GameRoute
  '/hire': typeof HireRoute
  '/projects': typeof ProjectsRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing': typeof WritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/game': typeof GameRoute
  '/hire': typeof HireRoute
  '/projects': typeof ProjectsRoute
  '/writing': typeof WritingRouteWithChildren
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cv'
    | '/game'
    | '/hire'
    | '/projects'
    | '/writing'
    | '/writing/$slug'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cv'
    | '/game'
    | '/hire'
    | '/projects'
    | '/writing/$slug'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/cv'
    | '/game'
    | '/hire'
    | '/projects'
    | '/writing'
    | '/writing/$slug'
    | '/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  GameRoute: typeof GameRoute
  HireRoute: typeof HireRoute
  ProjectsRoute: typeof ProjectsRoute
  WritingRoute: typeof WritingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof WritingRoute
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof WritingRoute
    }
  }
}

interface WritingRouteChildren {
  WritingSlugRoute: typeof WritingSlugRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

const WritingRouteChildren: WritingRouteChildren = {
  WritingSlugRoute: WritingSlugRoute,
  WritingIndexRoute: WritingIndexRoute,
}

const WritingRouteWithChildren =
  WritingRoute._addFileChildren(WritingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  GameRoute: GameRoute,
  HireRoute: HireRoute,
  ProjectsRoute: ProjectsRoute,
  WritingRoute: WritingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
